<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "contacts".
 *
 * @property int $id
 * @property string $firstname
 * @property string $lastname
 * @property string $number
 */
class Contacts extends \yii\db\ActiveRecord
{
    public $numbers = [];

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'contacts';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['firstname', 'lastname'], 'required'],
            [['firstname', 'lastname'], 'string', 'max' => 50],
            ['numbers', 'each', 'rule' => ['string']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'firstname' => 'Имя',
            'lastname' => 'Фамилия',
            'numbers' => 'Номера'
        ];
    }


    public function beforeSave($insert)
    {
        foreach ($this->numbers as $k => $number) {
            if ($number == "") {
                unset($this->numbers[$k]);
            }
        }
        $this->number = json_encode($this->numbers);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $this->numbers = json_decode($this->number, true);
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}
